// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddMissionsResponse = boolean;

export type AdvancedSettings = {
  allow_change_tailno: boolean;
  disable_events: boolean;
  allow_ownship_export: boolean;
  allow_object_export: boolean;
  pause_on_load: boolean;
  allow_sensor_export: boolean;
  event_Takeoff: boolean;
  pause_without_clients: boolean;
  client_outbound_limit: number;
  client_inbound_limit: number;
  server_can_screenshot: boolean;
  allow_players_pool: boolean;
  voice_chat_server: boolean;
  allow_change_skin: boolean;
  event_Connect: boolean;
  event_Ejecting: boolean;
  event_Kill: boolean;
  event_Crash: boolean;
  event_Role: boolean;
  resume_mode: number;
  maxPing: number;
  allow_trial_only_clients: boolean;
  allow_dynamic_radio: boolean;
  redPasswordHash: string | null;
  bluePasswordHash: string | null;
  redPassword: string | null;
  bluePassword: string | null;
};

export type ApiError = { message: string; code: string };

export type BanPlayerRequest = {
  id: number;
  reason: string;
  ucid: string;
  period: bigint;
};

export type BanPlayerResponse = boolean;

export type BannedPlayer = {
  banned_from: number;
  banned_until: number;
  ipaddr: string;
  name: string;
  reason: string;
  ucid: string;
};

export type BillingType = "hourly" | "monthly";

export type ComparisonOperator =
  | "Equal"
  | "NotEqual"
  | "GreaterThan"
  | "GreaterThanOrEqual"
  | "LessThan"
  | "LessThanOrEqual";

export type CreateInstanceRequest = {
  region: Region;
  product_id: string;
  billing_type: BillingType;
  settings: DcsSettingsPayload;
  active_mods: Array<string>;
  wanted_terrains: Array<Terrain>;
};

export type CreateTriggerRequest = {
  name: string;
  description: string | null;
  condition: TriggerCondition;
  action: TriggerAction;
};

export type CurrentRuntimeAction = "StartingMission" | "StartingServer";

export type DcsChatSafe = {
  id: number;
  player_id: number;
  player_name: string;
  message: string;
  is_historical: boolean;
  unix_time: bigint;
};

export type DcsRuntimeSafe = {
  current_action: CurrentRuntimeAction | null;
  last_full_update: number;
  paused: boolean;
  mission_info: GetMissionInfoResponse;
  missionList: Array<string>;
  missionTheatres: Array<string>;
  listStartIndex: number;
  listShuffle: boolean;
  listLoop: boolean;
  players: Players;
  server_id: number;
  mission_list: GetMissionListResponse;
  settings: Settings;
  ip: string;
};

export type DcsSettingsPayload = {
  initial_server_name: string;
  initial_server_password: string;
  initial_max_players: number;
  enable_io: boolean;
  enable_os: boolean;
  enable_lfs: boolean;
  initial_use_voice_chat: boolean;
};

export type DcsSettingsSafe = {
  initial_server_name: string;
  initial_server_password: string;
  initial_max_players: number;
  enable_io: boolean;
  enable_os: boolean;
  enable_lfs: boolean;
  initial_use_voice_chat: boolean;
};

export type DcsSettingsUpdatePayload = {
  enable_io: boolean;
  enable_os: boolean;
  enable_lfs: boolean;
};

export type DeleteMissionsResponse = {
  result: boolean;
  deleted_missions: Array<number>;
};

export type EditInstanceRequest = {
  game_type: "dcs";
  settings: DcsSettingsUpdatePayload;
};

export type FileInfo = {
  name: string;
  path: string;
  is_directory: boolean;
  size: number | null;
  modified: number | null;
};

export type FileListResponse = { files: Array<FileInfo>; current_path: string };

export type GameData = DcsRuntimeSafe;

export type GameType = "dcs";

export type GetMissionInfoResponse = {
  result_red: number | null;
  result_blue: number | null;
  mission_filename: string;
  mission_time: number;
  mission_name: string;
  mission_description: string;
};

export type GetMissionListResponse = {
  missionList: Array<string>;
  missionTheatres: Array<string>;
  listStartIndex: number;
  listShuffle: boolean;
  listLoop: boolean;
};

export type GetPauseServerResponse = null;

export type GetResumeServerResponse = null;

export type InstanceResource = {
  runtime: GameData | null;
  id: string;
  node_id: string;
  user_id: string;
  product_id: string;
  game_type: GameType;
  billing_type: BillingType;
  port: number;
  webgui_port: number;
  ftp_port: number;
  ftp_username: string;
  ftp_password: string;
  pid: number | null;
  status: InstanceStatus;
  want_delete: boolean;
  wanted_terrains: Array<Terrain>;
  rented_at: number;
  rented_until: number | null;
  active_mods: Array<string>;
  created_at: string;
  dcs_settings: DcsSettingsSafe | null;
  region: Region;
  ip: string;
  domain: string;
};

export type InstanceSafe = {
  id: string;
  node_id: string;
  user_id: string;
  product_id: string;
  game_type: GameType;
  billing_type: BillingType;
  port: number;
  webgui_port: number;
  ftp_port: number;
  ftp_username: string;
  ftp_password: string;
  pid: number | null;
  status: InstanceStatus;
  want_delete: boolean;
  wanted_terrains: Array<Terrain>;
  rented_at: number;
  rented_until: number | null;
  active_mods: Array<string>;
  created_at: string;
  dcs_settings: DcsSettingsSafe | null;
};

export type InstanceStatus =
  | "AwaitingContainer"
  | { InstallingBaseGame: { progress: number | null } }
  | {
      InstallingTerrains: {
        installed: Array<Terrain>;
        processing: Terrain | null;
        processing_progress: number | null;
        /**
         * If true, this is a post-creation terrain change and should return to ServerStopped after completion
         * If false, this is initial installation and should continue to InstallingMods
         */
        is_post_creation: boolean;
      };
    }
  | "InstallingMods"
  | "InstallingPost"
  | {
      UninstallingTerrains: {
        want_uninstall: Array<Terrain>;
        after_install: Array<Terrain>;
      };
    }
  | "ServerStarted"
  | { ServerStopped: { was_error: boolean; reason: InstanceStoppedReason } }
  | "ServerExpired"
  | "ServerDeleted"
  | { WantServerStarted: { current_try: number } }
  | {
      WantServerStopped: {
        error_passthrough: [boolean, InstanceStoppedReason] | null;
      };
    }
  | { WantUpdateServer: { was_stopped: boolean } };

export type InstanceStoppedReason =
  | "StoppedNormally"
  | "StoppedUnexpectedly"
  | "MaxTriesReached"
  | "ServerUpdating"
  | "RebootRequestedThroughFile"
  | "DcsSessionExpired"
  | { StoppedForRestart: { scheduled: boolean } };

export type InstancesResponse = Array<InstanceResource>;

export type KickPlayerRequest = { id: number; reason: string };

export type KickPlayerResponse = boolean;

export type MoveFileRequest = { source: string; destination: string };

export type Player = {
  ping: number;
  side: number;
  slot: string;
  id: number;
  name: string;
  score: number;
  ucid: string;
  started: boolean;
  lang: string;
  ipaddr: string;
};

export type Players = {
  banned: Array<BannedPlayer>;
  all: { [key in string]: Player };
};

export type PrometheusSeries = { values: Array<[number, string]> };

export type Region = "de" | "us" | "invalid";

export type SendChatRequest = { all: boolean; msg: string };

export type SendChatResponse = null;

export type ServerResourcesResponse = {
  cpus: Array<PrometheusSeries>;
  ram: Array<PrometheusSeries>;
  max_ram: number;
  players: Array<PrometheusSeries>;
  server_fps: Array<PrometheusSeries>;
};

export type SetServerSettingsRequest = Settings;

export type SetServerSettingsResponse = boolean;

export type Settings = {
  description: string;
  require_pure_textures: boolean;
  listStartIndex: number;
  advanced: AdvancedSettings;
  port: number;
  mode: number;
  bind_address: string;
  isPublic: boolean;
  listShuffle: boolean;
  password: string;
  listLoop: boolean;
  name: string;
  require_pure_scripts: boolean;
  missionList: Array<string>;
  require_pure_clients: boolean;
  require_pure_models: boolean;
  maxPlayers: number;
};

export type SrsClient = {
  ClientGuid: string;
  Name: string;
  Coalition: number;
  AllowRecord: boolean;
  Seat: number;
};

export type SrsModRequest = { guid: string };

export type SrsServerInfo = {
  Clients: Array<SrsClient>;
  ServerVersion: string;
};

export type StartMissionResponse = {
  mission_list: GetMissionListResponse;
  res: boolean;
};

export type StartServerResponse = {
  mission_list: GetMissionListResponse;
  res: number;
};

export type Terrain =
  | "Afghanistan"
  | "Caucasus"
  | "Falklands"
  | "Iraq"
  | "Kola"
  | "MarianaIslands"
  | "MarianaIslandsWWII"
  | "Nevada"
  | "Normandy"
  | "PersianGulf"
  | "Sinai"
  | "Syria"
  | "TheChannel"
  | "GermanyCW";

export type Trigger = {
  id: string | null;
  instance_id: string;
  name: string;
  description: string | null;
  condition: TriggerCondition;
  action: TriggerAction;
  /**
   * Last time this trigger was executed
   */
  last_executed_at: string | null;
  created_at: string;
  updated_at: string;
};

export type TriggerAction =
  | { type: "RestartInstance" }
  | { type: "StopInstance" }
  | { type: "ExecuteLuaScript"; params: { script: string } }
  | { type: "SendChatMessage"; params: { message: string } };

export type TriggerCondition =
  | {
      type: "PlayerCount";
      config: { operator: ComparisonOperator; threshold: number };
    }
  | { type: "OnEvent"; config: { event_type: string } }
  | { type: "Schedule"; config: { cron_expression: string } };

export type WebConsoleExecuteRequest = { code: string };
