// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdvancedSettings = {
  allow_change_tailno: boolean;
  disable_events: boolean;
  allow_ownship_export: boolean;
  allow_object_export: boolean;
  pause_on_load: boolean;
  allow_sensor_export: boolean;
  event_takeoff: boolean;
  pause_without_clients: boolean;
  client_outbound_limit: number;
  client_inbound_limit: number;
  server_can_screenshot: boolean;
  allow_players_pool: boolean;
  voice_chat_server: boolean;
  allow_change_skin: boolean;
  event_connect: boolean;
  event_ejecting: boolean;
  event_kill: boolean;
  event_crash: boolean;
  event_role: boolean;
  resume_mode: number;
  max_ping: number;
  allow_trial_only_clients: boolean;
  allow_dynamic_radio: boolean;
};
