// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BannedPlayer = {
  banned_from: bigint;
  banned_until: bigint;
  ipaddr: string;
  name: string;
  reason: string;
  ucid: string;
};
