// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CpuMetricData } from "./CpuMetricData";

export type CpuMetric = {
  metric: CpuMetricData;
  values: Array<[number, string]>;
};
