// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BillingType } from "./BillingType";
import type { DcsSettingsPayload } from "./DcsSettingsPayload";
import type { Region } from "./Region";
import type { Terrain } from "./Terrain";

export type CreateInstanceRequest = {
  product_id: string;
  region: Region;
  billing_type: BillingType;
  settings: DcsSettingsPayload;
  active_mods: Array<string>;
  wanted_terrains: Array<Terrain>;
};
