// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DcsChatSafe = {
  id: number;
  player_id: number;
  player_name: string;
  message: string;
  unix_time: bigint;
};
