// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MissionInfo } from "./MissionInfo";
import type { MissionList } from "./MissionList";
import type { PlayersResponse } from "./PlayersResponse";
import type { ServerSettings } from "./ServerSettings";

export type DcsRuntime = {
  paused: boolean;
  mission_info: MissionInfo | null;
  mission_list: MissionList | null;
  players: PlayersResponse | null;
  settings: ServerSettings | null;
};
