// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DcsCredentials } from "./DcsCredentials";

export type DcsSettingsPayload = {
  initial_server_name: string;
  initial_server_password: string;
  initial_max_players: number;
  use_own_credentials: boolean;
  credentials: DcsCredentials | null;
  initial_use_voice_chat: boolean;
};
