// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DcsSettingsPayload = {
  initial_server_name: string;
  initial_server_password: string;
  initial_max_players: number;
  enable_io: boolean;
  enable_os: boolean;
  enable_lfs: boolean;
  initial_use_voice_chat: boolean;
};
