// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DcsSettings = {
  server_name: string;
  server_password: string;
  max_players: number;
  use_own_credentials: boolean;
  credentials_username: string;
  credentials_password: string;
  use_voice_chat: boolean;
};
