// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DcsSettings } from "./DcsSettings";
import type { InstanceStatus } from "./InstanceStatus";
import type { Terrain } from "./Terrain";

export type Instance = {
  id: string;
  node_id: string;
  user_id: string;
  product_id: string;
  ip: string;
  port: number;
  webgui_port: number;
  ftp_port: number;
  ftp_username: string;
  ftp_password: string;
  pid: number | null;
  status: InstanceStatus;
  want_delete: boolean;
  wanted_terrains: Array<Terrain>;
  rented_at: bigint;
  rented_until: number | null;
  active_mods: Array<string>;
  created_at: string;
  dcs_settings: DcsSettings | null;
};
