// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceStoppedReason } from "./InstanceStoppedReason";
import type { Terrain } from "./Terrain";

export type InstanceStatus =
  | "AwaitingContainer"
  | { "InstallingBaseGame": { progress: number | null } }
  | {
    "InstallingTerrains": {
      installed: Array<Terrain>;
      processing: Terrain | null;
      processing_progress: number | null;
      is_post_creation: boolean;
    };
  }
  | "InstallingMods"
  | "InstallingPost"
  | {
    "UninstallingTerrains": {
      want_uninstall: Array<Terrain>;
      after_install: Array<Terrain>;
    };
  }
  | "ServerStarted"
  | { "ServerStopped": { was_error: boolean; reason: InstanceStoppedReason } }
  | "ServerExpired"
  | "ServerDeleted"
  | { "WantServerStarted": { current_try: number } }
  | {
    "WantServerStopped": {
      error_passthrough: [boolean, InstanceStoppedReason] | null;
    };
  }
  | { "WantUpdateServer": { was_stopped: boolean } };
