// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MissionInfo = {
  result_red: number | null;
  result_blue: number | null;
  mission_filename: string;
  mission_time: number;
  mission_name: string;
  mission_description: string;
};
