// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MissionList = {
  missionList: Array<string>;
  missionTheatres: Array<string>;
  listStartIndex: number;
  listShuffle: boolean;
  listLoop: boolean;
};
