// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Region } from "./Region";

export type Node = {
  id: string;
  name: string;
  region: Region;
  ip: string;
  port: number;
  max_cpu: number;
  max_ram: number;
};
