// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Players } from "./Players";

export type PlayersResponse = { players: Players; server_id: number };
