// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BannedPlayer } from "./BannedPlayer";
import type { Player } from "./Player";

export type Players = {
  banned: Array<BannedPlayer>;
  all: { [key in string]?: Player };
};
