// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Player = {
  ping: number;
  side: number;
  slot: string;
  id: number;
  name: string;
  score: number;
  ucid: string;
  started: boolean;
  lang: string;
  ipaddr: string;
};
