// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RamMetricData = {
  instance: string;
  job: string;
  monitor: string;
  vm_uuid: string;
};
