// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerResources = {
  cpus: Array<number>;
  memory: number;
  max_memory: number;
};
