// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CpuMetric } from "./CpuMetric";
import type { RamMetric } from "./RamMetric";

export type ServerResources = {
  cpus: Array<CpuMetric>;
  max_ram: bigint;
  ram: Array<RamMetric>;
};
