// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MissionList } from "./MissionList";
import type { Settings } from "./Settings";

export type ServerSettings = {
  mission_list: MissionList;
  settings: Settings;
  ip: string;
};
